backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img" # Ubicación donde se almacenarán los archivos en el repositorio
public_folder: "src/assets/img" # El atributo src para los medios cargados

collections: # A list of collections the CMS should be able to edit
  - name: "mentira" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Mentira" # Used in the UI, ie.: "New Post"
    folder: "src/content/mentira" # The path to the folder where the documents are stored
    preview_path: "src/content/mentira/{{slug}}"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../MentiraPost.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Slug", name: "postSlug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Lie Date", name: "lieDate", widget: "datetime" }
      - { label: "Lie Date Digo", name: "lieDateDigo", widget: "datetime" }
      - { label: "Youtube id", name: "youtubeId", widget: "string" }
      - { label: "Youtube title", name: "youtubeTitle", widget: "string" }